### PR TITLE
fix extracted files attributes

### PR DESCRIPTION
**Pull request by Slach**
fix https://github.com/integr8ly/grafana_plugins_init/issues/1

### CODE REVIEW

**Comment by Slach** [comment]
@pb82 please look to this PR

**Comment by pb82** [comment]
@Slach so the problem was that the extracted files lost their permissions and this plugin required the executable flag set?

**Comment by Slach** [comment]
@pb82 yep, most of the plugins which have backend golang part for alerting require execution attribute for golang plugin binary file

**Comment by Slach** [comment]
@pb82 could we merge this PR and make a new Docker image release?

**Comment by pb82** [comment]
Verified, thanks @Slach

**Pull request merged**
